version: '3'

services:
  achievement-helper-backend:
    image: node:dubnium-alpine
    volumes:
    - ./:/app
    working_dir: /app
    command: ["npm", "start"]
    environment:
      XBOX_KEY: "xxxx"
      STEAM_KEY: "xxxx"
      HALO5_KEY: "xxxx"
      LOL_KEY: "xxxx"
    ports:
    - 4420:4420
    networks:
    - achievement-helper
networks:
  achievement-helper:
    driver: bridge